title: Nico Kokonas
baseURL: "https://nicomee-modx.pages.dev/"
theme: PaperModX
timeZone: America/Denver

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false

googleAnalytics: G-PYQQ3SFW6E

minify:
  disableXML: true
  minifyOutput: false

params:
  description: "nicomee.com"
  author: nico
  images:
  - cover.png
  favicon: favicon.ico
  logo:
    icon: images/forge-v2-compat.svg
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  mainSections:
  - blog
  - essays
  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
  - twitter
  - telegram
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: nicomeemes@gmail.com

  socialIcons:
  - name: pinboard-simple
    url: "https://pinboard.in/u:nicoandmee"
  - name: github-simple
    url: "https://github.com/nicoandmee"
  - name: gitlab-simple
    url: "https://gitlab.com/nicoveritas"
  - name: twitter-simple
    url: "https://twitter.com/nicoandmee"
  - name: telegram-simple
    url: "https://t.me/radiumchemist"
  - name: mdi-resume
    url: "https://nicomee.com/resume.pdf"
  - name: stackoverflow
    url: "https://stackoverflow.com/users/6934588/nico-mee"
  - name: ycombinator
    url: "https://news.ycombinator.com/user?id=nicomeemes"
  - name: keybase
    url: "https://keybase.io/nicomee"
  - name: linkedin
    url: "https://www.linkedin.com/in/nico-kokonas/"
  - name: ycombinator
    url: "https://news.ycombinator.com/user?id=nicomeemes"
  - name: rss-simple
    url: "feed.xml"
  - name: stackoverflow-simple
    url: "https://stackoverflow.com/users/6934588/nico-mee"
  - name: gmail
    url: mailto:nicomeemes@gmail.com
  - name: goodreads
    url: "https://www.goodreads.com/user/show/144797700-nico-kokonas"

  links:
  - name: Julia Evans blog
    url: https://jvns.ca/
  - name: wzyboy’s blog
    url: https://awesomekling.github.io/
  - name: Andreas Kling blog

  socialAccounts:
    twitter:
      username: nicoandmee

  homeInfoParams:
    Title: "PaperModX"
    Content: |
      Welcome to demo of hugo's theme PaperModX.

      - **PaperModX** is a simple but fast and responsive theme with useful feature-set that enhances UX.

      - PaperModX is based on theme [PaperMod](https://github.com/adityatelange/hugo-PaperMod).

      To get started, please head to the [Docs](docs).

      To see examples of different contents, head to [examples tag](tags/example).

    commentSystems:
      disqus:
        shortname: nicomee
      remark42:
        url: https://nicomee.com
        site: nicomee.com
    defaultCommentSystems:
      remark42: true

permalinks:
  notes: /:section/:year/:month/:slugorcontentbasename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
  - name: Blog
    url: /blog/
    weight: 1
  - name: Essays
    url: /essays/
    weight: 2
  - name: Archives
    url: /archives/
    weight: 3
  # - name: Sponsors
  #   url: /sponsors/
  - name: Links
    url: /links/

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
